version: '3.8'

services:
  laravel-app:
    build:
      context: ./back/laravel
      dockerfile: ./DockerFile
    container_name: laravel
    working_dir: /var/www
    volumes:
      - ./back/laravel:/var/www
    command: >
      bash -c "composer update
      && echo 'iniciem'
      && php artisan key:generate
      && echo 'ini migracio'
      && php artisan migrate
      && echo 'fi migracio, aixequem servidor'
      && php artisan serve --host=0.0.0.0 --port=8000"
    ports:
      - "8000:8000"
    depends_on:
      - db

  nuxt-app:
    image: node:18-bullseye
    container_name: nuxt
    working_dir: /app
    volumes:
      - ./front/nuxt:/app
    ports:
      - "3000:3000"
    environment:
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true
    command: bash -c "npm install && npm run dev"

  db:
    image: mysql:latest
    container_name: mysql_db
    volumes:
      - db-data5:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: usuari_tmp
      MYSQL_PASSWORD: 1password
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    ports:
      - "8080:80"
    depends_on:
      - db
volumes:
  db-data5:
